version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es-hinrichs
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - 12375:9200
      - 12376:9300
    restart: unless-stopped
volumes:
  esdata1:
    driver: local